name:       cs340mp2

# By signing below, I pledge on my honor that I neither gave nor received any
# unauthorized assistance on the code contained in this repository.

author:     "Charlie S. Student"      # your name
maintainer: "csstudent@hawk.iit.edu"  # your IIT email

dependencies:
- base >= 4.7 && < 5
- array
- gloss
- hspec
- HUnit
- HUnit-approx
- QuickCheck

executables:
  mp2:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp2

library:
  source-dirs: src

tests:
  mp2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp2
